FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY ./ReportBotTelegram/*.csproj ./ReportBotTelegram/
RUN dotnet restore ./ReportBotTelegram/Report.csproj

COPY ./ReportBotTelegram/ ./ReportBotTelegram/
RUN dotnet publish ./ReportBotTelegram/Report.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Report.dll"]
