# Используйте базовый образ SDK для сборки и компиляции
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Копируйте csproj и восстанавливайте зависимости
COPY *.csproj ./
RUN dotnet restore

# Копируйте остальные файлы проекта
COPY . ./

# Соберите приложение
RUN dotnet publish -c Release -o out

# Стадия запуска
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Report.dll"]
