version: "3.8"
services:
  node-server:
    build:
      context: ./Node-Server
      dockerfile: Dockerfile
    ports:
      - "20203:20203"
    volumes:
      - ./Node-Server:/usr/src/app
    environment:
      NODE_ENV: production
      DATABASE_HOST: localhost
      DATABASE_USER: kirillok
      DATABASE_NAME: colorchessdb
      DATABASE_PASSWORD: loki5566
      SERVER_PORT: 20203
      SERVER_IP: localhost

  react-app:
    build:
      context: ./React-App
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - node-server
    environment:
      REACT_APP_SERVER_IP: localhost
      REACT_APP_SERVER_PORT: 20203
